{
		applicationNumber
		confirmedServiceEng
		confirmedServiceArb
		loanAmount
		applicationDate
		salutationEng 
		applicantNameEng
		applicantNameArb
		salutationArb
		emirateID
		emirateIDExpDate 		
		shortName
		khulasatAlQaidNumber
		applicantType
		applicantCount
		dateOfBirth
		applicantGender
		ralationWithPrimary
		birthPlaceAppPortal
		birthPlaceT24
		tradeLicenseNo
		monthlyIncome
		farmIncomeAmount
		tradeLicenseIncomeAmount
		mobileNumber
		emailAddress
		ownerPercentage
		town
		ownPlotAddress
		ownPlotNumber
		confMunicipalityEng
		confMunicipalityArb
		confDistrictEng
		confDistrictArb
		confCommunityEng
		confCommunityArb
		confPlotID
		motherNameEng
		motherNameArb
		unifiedNumber
		tribeEng
		tribeArb
		batchID
		passportNumber
		passportExpiryDate
		estimatedMonthlyInstalment
		loanCode
	}
